
import type { Metadata } from 'next'
import Navbar from './components/Navbar';
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by JongHeon',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html >
      <body >
        <Navbar/>
        <h1>ff</h1>
        {children}
        </body>
    </html>
  )
}
